# Copyright 2018 <chaishushan{AT}gmail.com>. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM openpitrix/caddy

COPY Caddyfile.local /etc/Caddyfile
COPY ./ /srv/chai2010.me/

WORKDIR /srv/chai2010.me/

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
